version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sportsinventorydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test@123
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn sports_inventory.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
